// vite-remoteapp-1/src/App.tsx
import "./App.css";
import TestComponent from "./components/TestComponent";

function App() {
  return (
    <div className="w-full h-full flex flex-col items-center justify-center">
      <span>Hi, i am remote application 1</span>
      <span>Vite + React + TS</span>
      <TestComponent />
    </div>
  );
}

export default App;

// vite-remoteapp-2/src/App.vue
<script setup lang="ts">
import NavBar from "./components/NavBar.vue";
</script>

<template>
  <div
    class="w-full h-full flex flex-col justify-center items-center bg-gradient-to-br from-blue-50 to-indigo-50 dark:from-gray-900 dark:to-indigo-950"
  >
    <div class="w-full h-auto flex-shrink-0">
      <NavBar />
    </div>
    <div class="w-full flex-grow overflow-y-auto">
      <router-view />
    </div>
  </div>
</template>

<style scoped></style>
