// vite-hostapp/src/App.vue
<script setup lang="ts">
import Navbar from "./components/Navbar/NavBar.vue";
import RemoteWrapper from "./remoteWrapper/RemoteWrapper.vue";
import SideMenu from "./components/SideMenu/SideMenu.vue";
</script>

<template>
  <div class="w-dvw h-dvh flex items-center justify-center">
    <div class="w-full md:w-16 h-16 md:h-full flex-shrink-0">
      <Navbar />
    </div>

    <div
      class="h-full flex-grow overflow-y-auto flex justify-center items-center"
    >
      remote app container
      <RemoteWrapper />
    </div>

    <SideMenu />
  </div>
</template>

<style scoped></style>

// vite-remoteapp-1/src/App.tsx
import "./App.css";
import TestComponent from "./components/TestComponent";

function App() {
  return (
    <div className="w-full h-full flex flex-col items-center justify-center">
      <span>Hi, i am remote application 1</span>
      <span>Vite + React + TS</span>
      <TestComponent />
    </div>
  );
}

export default App;
